  products:
  
  - text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, "
    image: "../images/product/1.svg"
    title: "Lorem Ipsum"
    weight: 1
  - text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, "
    image: "../images/product/2.svg"
    title: "Lorem Ipsum"
    weight: 2
  - text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, "
    image: "../images/product/3.svg"
    title: "Lorem Ipsum"
    weight: 3
  - text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, "
    image: "../images/product/4.svg"
    title: "Lorem Ipsum"
    weight: 4
  - text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, "
    image: "../images/product/5.svg"
    title: "Lorem Ipsum"
    weight: 5
  - text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, "
    image: "../images/product/6.svg"
    title: "Lorem Ipsum"
    weight: 6
  - text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, "
    image: "../images/product/7.svg"
    title: "Lorem Ipsum"
    weight: 7
  - text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, "
    image: "../images/product/7.svg"
    title: "Lorem Ipsum"  
    weight: 8
